name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_display: columns
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_OR_SOMETHING }}
          config_timezone: Asia/Manila
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          config_order: base.header, isocalendar, achievements, languages, topics
